steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/github.com/meriadok/onlinetest:$COMMIT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/github.com/meriadok/onlinetest:$COMMIT_SHA'


# deploy container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=kubeconfig.yml'
  - '--image=gcr.io/$PROJECT_ID/github.com/meriadok/onlinetest:$COMMIT_SHA'
  - '--location=southamerica-east1-a'
  - '--cluster=prueba23people-cluster'