apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: prueba23people
  name: prueba23people
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prueba23people
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prueba23people
    spec:
      containers:
      - image: gcr.io/premium-silicon-286916/github.com/meriadok/onlinetest:latest
        name: onlinetest-sha256-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30